// API Configuration
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000';

export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: `${API_BASE_URL}/auth/register`,
    LOGIN: `${API_BASE_URL}/auth/login`,
    CHECK_EMAIL: `${API_BASE_URL}/auth/check-email`,
    VERIFY_EMAIL: (userId: string) => `${API_BASE_URL}/auth/verify-email/${userId}`,
    RESEND_EMAIL_OTP: (userId: string) => `${API_BASE_URL}/auth/resend-email-otp/${userId}`,
    VERIFY_DEVICE: (userId: string) => `${API_BASE_URL}/auth/verify-device/${userId}`,
    CHECK_DEVICE: (userId: string) => `${API_BASE_URL}/auth/check-device/${userId}`,
    ACTIVATE_ACCOUNT: (userId: string) => `${API_BASE_URL}/auth/activate-account/${userId}`,
    GET_CURRENT_USER: `${API_BASE_URL}/auth/me`,
    LOGOUT: `${API_BASE_URL}/auth/logout`,
    UPDATE_PROFILE: `${API_BASE_URL}/auth/profile`,
    GOOGLE: `${API_BASE_URL}/auth/google`,
    FACEBOOK: `${API_BASE_URL}/auth/facebook`,
    APPLE: `${API_BASE_URL}/auth/apple`,
  },
  PROPERTY: {
    GET_ALL: `${API_BASE_URL}/property`,
    GET_ONE: (id: string) => `${API_BASE_URL}/property/${id}`,
    CREATE: `${API_BASE_URL}/property`,
    UPDATE: (id: string) => `${API_BASE_URL}/property/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/property/${id}`,
    GET_ALL_UNITS: `${API_BASE_URL}/property/units/all`,
  },
  UNIT: {
    GET_ALL_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/unit/property/${propertyId}`,
    GET_ONE: (id: string) => `${API_BASE_URL}/unit/${id}`,
    CREATE: (propertyId: string) => `${API_BASE_URL}/unit/property/${propertyId}`,
    UPDATE: (id: string) => `${API_BASE_URL}/unit/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/unit/${id}`,
  },
  UPLOAD: {
    FILE: `${API_BASE_URL}/upload/file`,
    IMAGE: `${API_BASE_URL}/upload/image`,
  },
  LEASING: {
    GET_ALL: `${API_BASE_URL}/leasing`,
    GET_ONE: (id: string) => `${API_BASE_URL}/leasing/${id}`,
    GET_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/leasing/property/${propertyId}`,
    CREATE: `${API_BASE_URL}/leasing`,
    UPDATE: (id: string) => `${API_BASE_URL}/leasing/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/leasing/${id}`,
  },
  LISTING: {
    GET_ALL: `${API_BASE_URL}/listing`,
    GET_ONE: (id: string) => `${API_BASE_URL}/listing/${id}`,
    GET_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/listing/property/${propertyId}`,
    CREATE: `${API_BASE_URL}/listing`,
    UPDATE: (id: string) => `${API_BASE_URL}/listing/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/listing/${id}`,
  },
  KEYS: {
    GET_ALL: `${API_BASE_URL}/keys-and-locks`,
    GET_ONE: (id: string) => `${API_BASE_URL}/keys-and-locks/${id}`,
    GET_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/keys-and-locks/property/${propertyId}`,
    GET_BY_UNIT: (unitId: string) => `${API_BASE_URL}/keys-and-locks/unit/${unitId}`,
    CREATE: `${API_BASE_URL}/keys-and-locks`,
    UPDATE: (id: string) => `${API_BASE_URL}/keys-and-locks/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/keys-and-locks/${id}`,
  },
  EQUIPMENT: {
    GET_ALL: `${API_BASE_URL}/equipment`,
    GET_ONE: (id: string) => `${API_BASE_URL}/equipment/${id}`,
    GET_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/equipment/property/${propertyId}`,
    GET_BY_UNIT: (unitId: string) => `${API_BASE_URL}/equipment/unit/${unitId}`,
    CREATE: `${API_BASE_URL}/equipment`,
    UPDATE: (id: string) => `${API_BASE_URL}/equipment/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/equipment/${id}`,
    GET_CATEGORIES: `${API_BASE_URL}/equipment/categories/all`,
    GET_SUBCATEGORIES: (categoryId: string) => `${API_BASE_URL}/equipment/categories/${categoryId}/subcategories`,
  },
  TENANT: {
    GET_ALL: `${API_BASE_URL}/tenant`,
    GET_ONE: (id: string) => `${API_BASE_URL}/tenant/${id}`,
    GET_BY_USER: (userId: string) => `${API_BASE_URL}/tenant/user/${userId}`,
    CREATE: `${API_BASE_URL}/tenant`,
    UPDATE: (id: string) => `${API_BASE_URL}/tenant/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/tenant/${id}`,
    UPLOAD_PROFILE_PHOTO: (id: string) => `${API_BASE_URL}/tenant/${id}/profile-photo`,
    UPLOAD_DOCUMENT: (id: string) => `${API_BASE_URL}/tenant/${id}/documents`,
    GET_DOCUMENTS: (id: string) => `${API_BASE_URL}/tenant/${id}/documents`,
    DELETE_DOCUMENT: (documentId: string) => `${API_BASE_URL}/tenant/documents/${documentId}`,
  },
  APPLICATION: {
    GET_ALL: `${API_BASE_URL}/application`,
    GET_ONE: (id: string) => `${API_BASE_URL}/application/${id}`,
    GET_BY_LEASING: (leasingId: string) => `${API_BASE_URL}/application/leasing/${leasingId}`,
    CREATE: `${API_BASE_URL}/application`,
    UPDATE: (id: string) => `${API_BASE_URL}/application/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/application/${id}`,
  },
  SERVICE_PROVIDER: {
    GET_ALL: `${API_BASE_URL}/service-provider`,
    GET_ONE: (id: string) => `${API_BASE_URL}/service-provider/${id}`,
    GET_BY_CATEGORY: (category: string) => `${API_BASE_URL}/service-provider/category/${category}`,
    CREATE: `${API_BASE_URL}/service-provider`,
    UPDATE: (id: string) => `${API_BASE_URL}/service-provider/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/service-provider/${id}`,
    UPLOAD_DOCUMENT: (id: string) => `${API_BASE_URL}/service-provider/${id}/documents`,
    GET_DOCUMENTS: (id: string) => `${API_BASE_URL}/service-provider/${id}/documents`,
    DELETE_DOCUMENT: (documentId: string) => `${API_BASE_URL}/service-provider/documents/${documentId}`,
  },
  TASK: {
    GET_ALL: `${API_BASE_URL}/task`,
    GET_ONE: (id: string) => `${API_BASE_URL}/task/${id}`,
    CREATE: `${API_BASE_URL}/task`,
    UPDATE: (id: string) => `${API_BASE_URL}/task/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/task/${id}`,
  },
  REMINDER: {
    GET_ALL: `${API_BASE_URL}/reminder`,
    GET_ONE: (id: string) => `${API_BASE_URL}/reminder/${id}`,
    CREATE: `${API_BASE_URL}/reminder`,
    UPDATE: (id: string) => `${API_BASE_URL}/reminder/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/reminder/${id}`,
  },
  CALENDAR: {
    GET_EVENTS: `${API_BASE_URL}/calendar/events`,
  },
};

