export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000';
export const CHAT_API_BASE_URL = import.meta.env.VITE_CHAT_API_BASE_URL || 'http://localhost:3001';
export const CHAT_WS_URL = import.meta.env.VITE_CHAT_WS_URL || 'ws://localhost:3001';

export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: `${API_BASE_URL}/auth/register`,
    REGISTER_TENANT: `${API_BASE_URL}/auth/register/tenant`,
    REGISTER_SERVICE_PRO: `${API_BASE_URL}/auth/register/service-pro`,
    LOGIN: `${API_BASE_URL}/auth/login`,
    CHECK_EMAIL: `${API_BASE_URL}/auth/check-email`,
    CHECK_TENANT_EMAIL: `${API_BASE_URL}/auth/check-tenant-email`,
    VERIFY_EMAIL: (userId: string) => `${API_BASE_URL}/auth/verify-email/${userId}`,
    RESEND_EMAIL_OTP: (userId: string) => `${API_BASE_URL}/auth/resend-email-otp/${userId}`,
    VERIFY_DEVICE: (userId: string) => `${API_BASE_URL}/auth/verify-device/${userId}`,
    RESEND_DEVICE_OTP: (userId: string) => `${API_BASE_URL}/auth/resend-device-otp/${userId}`,
    CHECK_DEVICE: (userId: string) => `${API_BASE_URL}/auth/check-device/${userId}`,
    ACTIVATE_ACCOUNT: (userId: string) => `${API_BASE_URL}/auth/activate-account/${userId}`,
    GET_CURRENT_USER: `${API_BASE_URL}/auth/me`,
    CHAT_TOKEN: `${API_BASE_URL}/auth/chat-token`,
    LOGOUT: `${API_BASE_URL}/auth/logout`,
    FORGOT_PASSWORD: `${API_BASE_URL}/auth/forgot-password`,
    RESET_PASSWORD: `${API_BASE_URL}/auth/reset-password`,
    CHANGE_PASSWORD: `${API_BASE_URL}/auth/change-password`,
    CHANGE_EMAIL: `${API_BASE_URL}/auth/change-email`,
    UPDATE_PROFILE: `${API_BASE_URL}/auth/profile`,
    DELETE_ACCOUNT: `${API_BASE_URL}/auth/account`,
    VERIFY_MOBILE_TOKEN: `${API_BASE_URL}/auth/verify-mobile-token`,
    INVITE_LANDLORD: `${API_BASE_URL}/auth/invite-landlord`,
    GOOGLE: `${API_BASE_URL}/auth/google`,
    FACEBOOK: `${API_BASE_URL}/auth/facebook`,
    APPLE: `${API_BASE_URL}/auth/apple`,
  },
  PROPERTY: {
    GET_ALL: `${API_BASE_URL}/property`,
    GET_ALL_ID_NAME: `${API_BASE_URL}/property?ispropertyidname=true`,
    GET_ONE: (id: string) => `${API_BASE_URL}/property/${id}`,
    CREATE: `${API_BASE_URL}/property`,
    UPDATE: (id: string) => `${API_BASE_URL}/property/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/property/${id}`,
    BULK_DELETE: `${API_BASE_URL}/property/bulk/delete`,
    GET_ALL_UNITS: `${API_BASE_URL}/property/units/all`,
    IMPORT_EXCEL: `${API_BASE_URL}/property/import-excel`,
    VALIDATE_EXCEL: `${API_BASE_URL}/property/validate-excel`,
    GET_IMPORT_FIELDS: `${API_BASE_URL}/property/import-fields`,
    GET_PUBLIC_LISTINGS: `${API_BASE_URL}/property/public/listings`,
    GET_PUBLIC_DETAIL: (id: string) => `${API_BASE_URL}/property/public/${id}`,
    // Property detail tabs
    GET_SPECS: (id: string) => `${API_BASE_URL}/property/${id}/specs`,
    CREATE_SPEC: (id: string) => `${API_BASE_URL}/property/${id}/specs`,
    UPDATE_SPEC: (id: string, specId: string) => `${API_BASE_URL}/property/${id}/specs/${specId}`,
    DELETE_SPEC: (id: string, specId: string) => `${API_BASE_URL}/property/${id}/specs/${specId}`,
    GET_FINANCIALS: (id: string) => `${API_BASE_URL}/property/${id}/financials`,
    CREATE_INSURANCE: (id: string) => `${API_BASE_URL}/property/${id}/insurances`,
    UPDATE_INSURANCE: (id: string, insuranceId: string) => `${API_BASE_URL}/property/${id}/insurances/${insuranceId}`,
    DELETE_INSURANCE: (id: string, insuranceId: string) => `${API_BASE_URL}/property/${id}/insurances/${insuranceId}`,
    CREATE_LOAN: (id: string) => `${API_BASE_URL}/property/${id}/loans`,
    UPDATE_LOAN: (id: string, loanId: string) => `${API_BASE_URL}/property/${id}/loans/${loanId}`,
    DELETE_LOAN: (id: string, loanId: string) => `${API_BASE_URL}/property/${id}/loans/${loanId}`,
    GET_SERVICE_PROVIDERS: (id: string) => `${API_BASE_URL}/property/${id}/service-providers`,
    CREATE_UTILITY_PROVIDER: (id: string) => `${API_BASE_URL}/property/${id}/utility-providers`,
    UPDATE_UTILITY_PROVIDER: (id: string, providerId: string) => `${API_BASE_URL}/property/${id}/utility-providers/${providerId}`,
    DELETE_UTILITY_PROVIDER: (id: string, providerId: string) => `${API_BASE_URL}/property/${id}/utility-providers/${providerId}`,
    GET_RESPONSIBILITIES: (id: string) => `${API_BASE_URL}/property/${id}/responsibilities`,
    UPSERT_RESPONSIBILITIES: (id: string) => `${API_BASE_URL}/property/${id}/responsibilities`,
  },
  UNIT: {
    GET_ALL_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/unit/property/${propertyId}`,
    GET_ONE: (id: string) => `${API_BASE_URL}/unit/${id}`,
    CREATE: (propertyId: string) => `${API_BASE_URL}/unit/property/${propertyId}`,
    UPDATE: (id: string) => `${API_BASE_URL}/unit/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/unit/${id}`,
    // Unit detail tabs
    GET_SPECS: (id: string) => `${API_BASE_URL}/unit/${id}/specs`,
    GET_FINANCIALS: (id: string) => `${API_BASE_URL}/unit/${id}/financials`,
    GET_SERVICE_PROVIDERS: (id: string) => `${API_BASE_URL}/unit/${id}/service-providers`,
  },
  UPLOAD: {
    FILE: `${API_BASE_URL}/upload/file`,
    IMAGE: `${API_BASE_URL}/upload/image`,
  },
  MAINTENANCE_REQUEST: {
    CREATE: `${API_BASE_URL}/maintenance-request`,
    GET_ALL: `${API_BASE_URL}/maintenance-request`,
    GET_ONE: (id: string) => `${API_BASE_URL}/maintenance-request/${id}`,
    UPDATE: (id: string) => `${API_BASE_URL}/maintenance-request/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/maintenance-request/${id}`,
    LIST_TRANSACTIONS: (id: string) => `${API_BASE_URL}/maintenance-request/${id}/transactions`,
    CREATE_TRANSACTION: (id: string) => `${API_BASE_URL}/maintenance-request/${id}/transactions`,
    APPROVE_TENANT_CHARGE: (id: string) => `${API_BASE_URL}/maintenance-request/${id}/approve-tenant-charge`,
    ASSIGN_INTERNAL: (id: string) => `${API_BASE_URL}/maintenance-request/${id}/assign-internal`,
    GET_APPLICANTS: (id: string) => `${API_BASE_URL}/maintenance-request/${id}/applicants`,
  },
  LEASING: {
    GET_ALL: `${API_BASE_URL}/leasing`,
    GET_ONE: (id: string) => `${API_BASE_URL}/leasing/${id}`,
    GET_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/leasing/property/${propertyId}`,
    CREATE: `${API_BASE_URL}/leasing`,
    UPDATE: (id: string) => `${API_BASE_URL}/leasing/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/leasing/${id}`,
    IMPORT_EXCEL: `${API_BASE_URL}/leasing/import-excel`,
    VALIDATE_EXCEL: `${API_BASE_URL}/leasing/validate-excel`,
    GET_IMPORT_FIELDS: `${API_BASE_URL}/leasing/import-fields`,
  },
  LISTING: {
    GET_ALL: `${API_BASE_URL}/listing`,
    DASHBOARD_VIEW: `${API_BASE_URL}/listing/dashboard-view`,
    GET_ONE: (id: string) => `${API_BASE_URL}/listing/${id}`,
    GET_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/listing/property/${propertyId}`,
    CREATE: `${API_BASE_URL}/listing`,
    UPDATE: (id: string) => `${API_BASE_URL}/listing/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/listing/${id}`,
    GET_STATISTICS: (id: string) => `${API_BASE_URL}/listing/${id}/statistics`,
    TOGGLE_FAVORITE: (id: string) => `${API_BASE_URL}/listing/${id}/favorite`,
    IS_FAVORITED: (id: string) => `${API_BASE_URL}/listing/${id}/favorite`,
    MY_FAVORITES: `${API_BASE_URL}/listing/favorites/mine`,
  },
  KEYS: {
    GET_ALL: `${API_BASE_URL}/keys-and-locks`,
    GET_ONE: (id: string) => `${API_BASE_URL}/keys-and-locks/${id}`,
    GET_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/keys-and-locks/property/${propertyId}`,
    GET_BY_UNIT: (unitId: string) => `${API_BASE_URL}/keys-and-locks/unit/${unitId}`,
    CREATE: `${API_BASE_URL}/keys-and-locks`,
    UPDATE: (id: string) => `${API_BASE_URL}/keys-and-locks/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/keys-and-locks/${id}`,
  },
  EQUIPMENT: {
    GET_ALL: `${API_BASE_URL}/equipment`,
    GET_ONE: (id: string) => `${API_BASE_URL}/equipment/${id}`,
    GET_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/equipment/property/${propertyId}`,
    GET_BY_UNIT: (unitId: string) => `${API_BASE_URL}/equipment/unit/${unitId}`,
    CREATE: `${API_BASE_URL}/equipment`,
    UPDATE: (id: string) => `${API_BASE_URL}/equipment/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/equipment/${id}`,
    GET_CATEGORIES: `${API_BASE_URL}/equipment/categories/all`,
    GET_SUBCATEGORIES: (categoryId: string) => `${API_BASE_URL}/equipment/categories/${categoryId}/subcategories`,
  },
  TENANT: {
    GET_ALL: `${API_BASE_URL}/tenant`,
    GET_ONE: (id: string) => `${API_BASE_URL}/tenant/${id}`,
    GET_BY_USER: (userId: string) => `${API_BASE_URL}/tenant/user/${userId}`,
    CREATE: `${API_BASE_URL}/tenant`,
    UPDATE: (id: string) => `${API_BASE_URL}/tenant/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/tenant/${id}`,
    UPLOAD_PROFILE_PHOTO: (id: string) => `${API_BASE_URL}/tenant/${id}/profile-photo`,
    UPLOAD_DOCUMENT: (id: string) => `${API_BASE_URL}/tenant/${id}/documents`,
    GET_DOCUMENTS: (id: string) => `${API_BASE_URL}/tenant/${id}/documents`,
    DELETE_DOCUMENT: (documentId: string) => `${API_BASE_URL}/tenant/documents/${documentId}`,
    SAVE_PREFERENCES: `${API_BASE_URL}/tenant/preferences`,
    GET_PREFERENCES: `${API_BASE_URL}/tenant/preferences`,
    MY_DASHBOARD: `${API_BASE_URL}/tenant/me/dashboard`,
    IMPORT_EXCEL: `${API_BASE_URL}/tenant/import-excel`,
    VALIDATE_EXCEL: `${API_BASE_URL}/tenant/validate-excel`,
    GET_IMPORT_FIELDS: `${API_BASE_URL}/tenant/import-fields`,
  },
  APPLICATION: {
    GET_ALL: `${API_BASE_URL}/application`,
    GET_ONE: (id: string) => `${API_BASE_URL}/application/${id}`,
    GET_BY_LEASING: (leasingId: string) => `${API_BASE_URL}/application/leasing/${leasingId}`,
    GET_INVITATIONS: `${API_BASE_URL}/application/invitations`,
    GET_BACKGROUND_QUESTIONS: (propertyId: string) => `${API_BASE_URL}/application/property/${propertyId}/background-questions`,
    CREATE: `${API_BASE_URL}/application`,
    UPDATE: (id: string) => `${API_BASE_URL}/application/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/application/${id}`,
    INVITE: `${API_BASE_URL}/application/invite`,
    GET_ATTACHMENTS: (id: string) => `${API_BASE_URL}/application/${id}/attachments`,
    DELETE_ATTACHMENT: (id: string, attachmentId: string) => `${API_BASE_URL}/application/${id}/attachments/${attachmentId}`,
  },
  SERVICE_PROVIDER: {
    GET_ALL: `${API_BASE_URL}/service-provider`,
    GET_ONE: (id: string) => `${API_BASE_URL}/service-provider/${id}`,
    SELF_REGISTER: `${API_BASE_URL}/service-provider/self-register`,
    GET_PENDING: `${API_BASE_URL}/service-provider/pending`,
    APPROVE: (id: string) => `${API_BASE_URL}/service-provider/${id}/approve`,
    REJECT: (id: string) => `${API_BASE_URL}/service-provider/${id}/reject`,
    GET_ME_ASSIGNMENTS: `${API_BASE_URL}/service-provider/me/assignments`,
    GET_AVAILABLE_JOBS: `${API_BASE_URL}/service-provider/me/available-jobs`,
    GET_AVAILABLE_JOB_BY_ID: (requestId: string) => `${API_BASE_URL}/service-provider/me/available-jobs/${requestId}`,
    APPLY_TO_JOB: (requestId: string) => `${API_BASE_URL}/service-provider/me/available-jobs/${requestId}/apply`,
    GET_MY_PROFILE: `${API_BASE_URL}/service-provider/me/profile`,
    CREATE_OR_UPDATE_MY_PROFILE: `${API_BASE_URL}/service-provider/me/profile`,
    GET_MY_DASHBOARD_STATS: `${API_BASE_URL}/service-provider/me/dashboard-stats`,
    GET_MY_ACCOUNTING: `${API_BASE_URL}/service-provider/me/accounting`,
    UPDATE_ASSIGNMENT_STATUS: (id: string, assignmentId: string) => `${API_BASE_URL}/service-provider/${id}/assignments/${assignmentId}/status`,
    GET_BY_CATEGORY: (category: string) => `${API_BASE_URL}/service-provider/category/${category}`,
    ASSIGN_TO_REQUEST: (id: string, requestId: string) => `${API_BASE_URL}/service-provider/${id}/assignments/${requestId}`,
    ADD_TO_CONTACT: (id: string) => `${API_BASE_URL}/service-provider/${id}/add-to-contact`,
    CREATE: `${API_BASE_URL}/service-provider`,
    UPDATE: (id: string) => `${API_BASE_URL}/service-provider/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/service-provider/${id}`,
    UPLOAD_DOCUMENT: (id: string) => `${API_BASE_URL}/service-provider/${id}/documents`,
    GET_DOCUMENTS: (id: string) => `${API_BASE_URL}/service-provider/${id}/documents`,
    DELETE_DOCUMENT: (documentId: string) => `${API_BASE_URL}/service-provider/documents/${documentId}`,
    IMPORT_EXCEL: `${API_BASE_URL}/service-provider/import-excel`,
    VALIDATE_EXCEL: `${API_BASE_URL}/service-provider/validate-excel`,
    GET_IMPORT_FIELDS: `${API_BASE_URL}/service-provider/import-fields`,
  },
  TASK: {
    GET_ALL: `${API_BASE_URL}/task`,
    GET_ONE: (id: string) => `${API_BASE_URL}/task/${id}`,
    CREATE: `${API_BASE_URL}/task`,
    UPDATE: (id: string) => `${API_BASE_URL}/task/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/task/${id}`,
  },
  REMINDER: {
    GET_ALL: `${API_BASE_URL}/reminder`,
    GET_ONE: (id: string) => `${API_BASE_URL}/reminder/${id}`,
    CREATE: `${API_BASE_URL}/reminder`,
    UPDATE: (id: string) => `${API_BASE_URL}/reminder/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/reminder/${id}`,
  },
  CALENDAR: {
    GET_EVENTS: `${API_BASE_URL}/calendar/events`,
  },
  LEAD: {
    GET_ALL: `${API_BASE_URL}/leads`,
    GET_ONE: (id: string) => `${API_BASE_URL}/leads/${id}`,
    CREATE: `${API_BASE_URL}/leads`,
    UPDATE: (id: string) => `${API_BASE_URL}/leads/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/leads/${id}`,
    // Notes endpoints
    NOTES: {
      GET_ALL: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/notes`,
      GET_ONE: (leadId: string, noteId: string) => `${API_BASE_URL}/leads/${leadId}/notes/${noteId}`,
      CREATE: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/notes`,
      UPDATE: (leadId: string, noteId: string) => `${API_BASE_URL}/leads/${leadId}/notes/${noteId}`,
      DELETE: (leadId: string, noteId: string) => `${API_BASE_URL}/leads/${leadId}/notes/${noteId}`,
    },
    // Tasks endpoints
    TASKS: {
      GET_ALL: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/tasks`,
      GET_ONE: (leadId: string, taskId: string) => `${API_BASE_URL}/leads/${leadId}/tasks/${taskId}`,
      CREATE: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/tasks`,
      UPDATE: (leadId: string, taskId: string) => `${API_BASE_URL}/leads/${leadId}/tasks/${taskId}`,
      DELETE: (leadId: string, taskId: string) => `${API_BASE_URL}/leads/${leadId}/tasks/${taskId}`,
    },
    // Activities endpoints
    ACTIVITIES: {
      GET_ALL: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/activities`,
      GET_ONE: (leadId: string, activityId: string) => `${API_BASE_URL}/leads/${leadId}/activities/${activityId}`,
      CREATE: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/activities`,
      DELETE: (leadId: string, activityId: string) => `${API_BASE_URL}/leads/${leadId}/activities/${activityId}`,
    },
    // Calls endpoints
    CALLS: {
      GET_ALL: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/calls`,
      GET_ONE: (leadId: string, callId: string) => `${API_BASE_URL}/leads/${leadId}/calls/${callId}`,
      CREATE: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/calls`,
      UPDATE: (leadId: string, callId: string) => `${API_BASE_URL}/leads/${leadId}/calls/${callId}`,
      DELETE: (leadId: string, callId: string) => `${API_BASE_URL}/leads/${leadId}/calls/${callId}`,
    },
    // Meetings endpoints
    MEETINGS: {
      GET_ALL: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/meetings`,
      GET_ONE: (leadId: string, meetingId: string) => `${API_BASE_URL}/leads/${leadId}/meetings/${meetingId}`,
      CREATE: (leadId: string) => `${API_BASE_URL}/leads/${leadId}/meetings`,
      UPDATE: (leadId: string, meetingId: string) => `${API_BASE_URL}/leads/${leadId}/meetings/${meetingId}`,
      DELETE: (leadId: string, meetingId: string) => `${API_BASE_URL}/leads/${leadId}/meetings/${meetingId}`,
    },
  },
  SUBSCRIPTION: {
    GET_CURRENT: `${API_BASE_URL}/subscription/current`,
    UPDATE: `${API_BASE_URL}/subscription/update`,
    CHANGE_PLAN: `${API_BASE_URL}/subscription/change-plan`,
    RENEW: `${API_BASE_URL}/subscription/renew`,
    BILLING_HISTORY: `${API_BASE_URL}/subscription/billing-history`,
  },
  LEASE: {
    GET_ALL: `${API_BASE_URL}/leases`,
    GET_ONE: (id: string) => `${API_BASE_URL}/leases/${id}`,
    GET_BY_PROPERTY: (propertyId: string) => `${API_BASE_URL}/leases?propertyId=${propertyId}`,
    GET_BY_TENANT: (tenantId: string) => `${API_BASE_URL}/leases?tenantId=${tenantId}`,
    CREATE: `${API_BASE_URL}/leases`,
    UPDATE: (id: string) => `${API_BASE_URL}/leases/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/leases/${id}`,
    UPDATE_UTILITIES: (id: string) => `${API_BASE_URL}/leases/${id}/utilities`,
    UPDATE_INSURANCES: (id: string) => `${API_BASE_URL}/leases/${id}/insurances`,
    RENEW: (id: string) => `${API_BASE_URL}/leases/${id}/renew`,
  },
  TRANSACTION: {
    CREATE_INCOME_INVOICE: `${API_BASE_URL}/transactions/income-invoice`,
    CREATE_EXPENSE_INVOICE: `${API_BASE_URL}/transactions/expense-invoice`,
    CREATE_RECURRING_INCOME: `${API_BASE_URL}/transactions/recurring-income`,
    CREATE_DEPOSIT: `${API_BASE_URL}/transactions/deposit`,
    CREATE_CREDIT: `${API_BASE_URL}/transactions/credit`,
    GET_TAGS: `${API_BASE_URL}/transactions/tags`,
    GET_PAYMENTS: `${API_BASE_URL}/transactions/payments`,
    GET_MY_FINANCE_SUMMARY: `${API_BASE_URL}/transactions/me/finance-summary`,
    GET_ALL: `${API_BASE_URL}/transactions`,
    GET_ONE: (id: string) => `${API_BASE_URL}/transactions/${id}`,
    GET_RECURRING: `${API_BASE_URL}/transactions/recurring`,
    GET_RECURRING_ONE: (id: string) => `${API_BASE_URL}/transactions/recurring/${id}`,
    DELETE_RECURRING: (id: string) => `${API_BASE_URL}/transactions/recurring/${id}`,
    END_RECURRING: (id: string) => `${API_BASE_URL}/transactions/recurring/${id}/end`,
    POST_NEXT_INVOICE: (id: string) => `${API_BASE_URL}/transactions/recurring/${id}/post-next-invoice`,
    GET_RETURNABLE_DEPOSITS: `${API_BASE_URL}/transactions/returnable-deposits`,
    RETURN_DEPOSIT: `${API_BASE_URL}/transactions/return-deposit`,
    GET_APPLICABLE_INVOICES: `${API_BASE_URL}/transactions/applicable-invoices`,
    GET_AVAILABLE_DEPOSITS_CREDITS: `${API_BASE_URL}/transactions/available-deposits-credits`,
    GET_TENANT_AGGREGATES: (tenantUserId: string) => `${API_BASE_URL}/transactions/aggregates/tenant/${tenantUserId}`,
    GET_SERVICE_PRO_AGGREGATES: (serviceProUserId: string) => `${API_BASE_URL}/transactions/aggregates/service-pro/${serviceProUserId}`,
    APPLY_DEPOSIT_CREDIT: `${API_BASE_URL}/transactions/apply-deposit-credit`,
    MARK_AS_PAID: (id: string) => `${API_BASE_URL}/transactions/${id}/mark-as-paid`,
    UPDATE: (id: string) => `${API_BASE_URL}/transactions/${id}`,
    UPDATE_DISCOUNT: (id: string) => `${API_BASE_URL}/transactions/${id}/discount`,
    VOID: (id: string) => `${API_BASE_URL}/transactions/${id}/void`,
    UPDATE_PAYMENT: (id: string, paymentId: string) => `${API_BASE_URL}/transactions/${id}/payment/${paymentId}`,
    DELETE_PAYMENT: (id: string, paymentId: string) => `${API_BASE_URL}/transactions/${id}/payment/${paymentId}`,
    REFUND_PAYMENT: (id: string, paymentId: string) => `${API_BASE_URL}/transactions/${id}/payment/${paymentId}/refund`,
    DELETE: (id: string) => `${API_BASE_URL}/transactions/${id}`,
  },
  CHAT: {
    BASE: CHAT_API_BASE_URL,
    WS: CHAT_WS_URL,
    CONVERSATIONS: `${CHAT_API_BASE_URL}/api/conversations`,
    CONVERSATION: (id: string) => `${CHAT_API_BASE_URL}/api/conversations/${id}`,
    MESSAGES: (id: string) => `${CHAT_API_BASE_URL}/api/conversations/${id}/messages`,
    MARK_READ: (id: string) => `${CHAT_API_BASE_URL}/api/conversations/${id}/read`,
    PRESENCE: `${CHAT_API_BASE_URL}/api/presence`,
  },
  CONTACT_BOOK: {
    GET_ALL: `${API_BASE_URL}/contact-book`,
  },
  GOOGLE_CALENDAR: {
    CONNECT: `${API_BASE_URL}/google-calendar/connect`,
    CALLBACK: `${API_BASE_URL}/google-calendar/callback`,
    STATUS: `${API_BASE_URL}/google-calendar/status`,
    DISCONNECT: `${API_BASE_URL}/google-calendar/disconnect`,
    SYNC_EVENTS: `${API_BASE_URL}/google-calendar/events/sync`,
    CREATE_EVENT: `${API_BASE_URL}/google-calendar/events`,
  },
  BACKGROUND_QUESTIONS: {
    GET_ALL: `${API_BASE_URL}/background-questions`,
    GET_ONE: (id: string) => `${API_BASE_URL}/background-questions/${id}`,
    CREATE: `${API_BASE_URL}/background-questions`,
    UPDATE: (id: string) => `${API_BASE_URL}/background-questions/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/background-questions/${id}`,
    REORDER: `${API_BASE_URL}/background-questions/reorder`,
  },
  DASHBOARD: {
    GET_STATS: `${API_BASE_URL}/dashboard`,
  },
  TEAM: {
    GET_ALL: `${API_BASE_URL}/team`,
    GET_ONE: (id: string) => `${API_BASE_URL}/team/${id}`,
    INVITE: `${API_BASE_URL}/team`,
    UPDATE: (id: string) => `${API_BASE_URL}/team/${id}`,
    REVOKE: (id: string) => `${API_BASE_URL}/team/${id}/revoke`,
    RESEND: (id: string) => `${API_BASE_URL}/team/${id}/resend-invitation`,
    DELETE: (id: string) => `${API_BASE_URL}/team/${id}`,
    ACCEPT_INVITATION: `${API_BASE_URL}/team/accept-invitation`,
    MY_TEAMS: `${API_BASE_URL}/team/my-teams`,
  },
  NOTIFICATION: {
    GET_ALL: `${API_BASE_URL}/notifications`,
    GET_SETTINGS: `${API_BASE_URL}/notifications/settings`,
    UPDATE_SETTINGS: `${API_BASE_URL}/notifications/settings`,
    GET_ONE: (id: string) => `${API_BASE_URL}/notifications/${id}`,
    MARK_READ: (id: string) => `${API_BASE_URL}/notifications/${id}/read`,
    MARK_ALL_READ: `${API_BASE_URL}/notifications/read-all`,
    DELETE: (id: string) => `${API_BASE_URL}/notifications/${id}`,
  },
  SETTINGS: {
    GET_SECTION: (section: string) => `${API_BASE_URL}/settings/${section}`,
    UPDATE_SECTION: (section: string) => `${API_BASE_URL}/settings/${section}`,
    SECURITY_SESSIONS: `${API_BASE_URL}/settings/security/sessions`,
  },
  AI_CHAT: {
    STREAM: `${import.meta.env.VITE_AI_CHAT_API_URL || 'http://localhost:8000'}/chat/stream`,
    CHAT: `${import.meta.env.VITE_AI_CHAT_API_URL || 'http://localhost:8000'}/chat`,
  },
  PAYMENTS: {
    CREATE_SETUP_INTENT: `${API_BASE_URL}/payments/setup-intent`,
    SAVE_CARD: `${API_BASE_URL}/payments/cards`,
    LIST_CARDS: `${API_BASE_URL}/payments/cards`,
    SET_DEFAULT: (id: string) => `${API_BASE_URL}/payments/cards/${id}/default`,
    DELETE_CARD: (id: string) => `${API_BASE_URL}/payments/cards/${id}`,
    CREATE_PAYMENT_INTENT: `${API_BASE_URL}/payments/payment-intent`,
    CONNECT_ONBOARDING_LINK: `${API_BASE_URL}/payments/connect/onboarding-link`,
    CONNECT_STATUS: `${API_BASE_URL}/payments/connect/status`,
    CONNECT_DISCONNECT: `${API_BASE_URL}/payments/connect/disconnect`,
  },
  TWO_FACTOR: {
    STATUS: `${API_BASE_URL}/2fa/status`,
    SEND_CODE: `${API_BASE_URL}/2fa/send-code`,
    VERIFY: `${API_BASE_URL}/2fa/verify`,
  },
  EQUIPMENT_ATTACHMENTS: {
    LIST: (equipmentId: string) => `${API_BASE_URL}/equipment/${equipmentId}/attachments`,
    ADD: (equipmentId: string) => `${API_BASE_URL}/equipment/${equipmentId}/attachments`,
    DELETE: (attachmentId: string) => `${API_BASE_URL}/equipment/attachments/${attachmentId}`,
  },
  MAINTENANCE_RECURRING: {
    GET_ALL: `${API_BASE_URL}/api/v1/maintenance-recurring`,
    GET_ONE: (id: string) => `${API_BASE_URL}/api/v1/maintenance-recurring/${id}`,
    CREATE: `${API_BASE_URL}/api/v1/maintenance-recurring`,
    UPDATE: (id: string) => `${API_BASE_URL}/api/v1/maintenance-recurring/${id}`,
    DELETE: (id: string) => `${API_BASE_URL}/api/v1/maintenance-recurring/${id}`,
  },
  FILES: {
    LIST_FOLDERS: `${API_BASE_URL}/api/v1/files/folders`,
    CREATE_FOLDER: `${API_BASE_URL}/api/v1/files/folders`,
    RENAME_FOLDER: (id: string) => `${API_BASE_URL}/api/v1/files/folders/${id}`,
    DELETE_FOLDER: (id: string) => `${API_BASE_URL}/api/v1/files/folders/${id}`,
    LIST_FILES: `${API_BASE_URL}/api/v1/files`,
    UPLOAD: `${API_BASE_URL}/api/v1/files/upload`,
    RENAME_FILE: (id: string) => `${API_BASE_URL}/api/v1/files/${id}`,
    DELETE_FILE: (id: string) => `${API_BASE_URL}/api/v1/files/${id}`,
  },
  DOCUMENTS: {
    LIST_TEMPLATES: `${API_BASE_URL}/api/v1/documents/templates`,
    GET_TEMPLATE: (id: string) => `${API_BASE_URL}/api/v1/documents/templates/${id}`,
    CREATE_TEMPLATE: `${API_BASE_URL}/api/v1/documents/templates`,
    UPDATE_TEMPLATE: (id: string) => `${API_BASE_URL}/api/v1/documents/templates/${id}`,
    DELETE_TEMPLATE: (id: string) => `${API_BASE_URL}/api/v1/documents/templates/${id}`,
    RENDER_TEMPLATE: (id: string) => `${API_BASE_URL}/api/v1/documents/templates/${id}/render`,
    LIST_RENDERED: `${API_BASE_URL}/api/v1/documents/rendered`,
    GET_RENDERED: (id: string) => `${API_BASE_URL}/api/v1/documents/rendered/${id}`,
    DELETE_RENDERED: (id: string) => `${API_BASE_URL}/api/v1/documents/rendered/${id}`,
  },
  REPORTS: {
    RENT_ROLL: `${API_BASE_URL}/api/v1/reports/rent-roll`,
    GENERAL_INCOME: (params: string) => `${API_BASE_URL}/api/v1/reports/general-income${params}`,
    GENERAL_EXPENSES: (params: string) => `${API_BASE_URL}/api/v1/reports/general-expenses${params}`,
    PROPERTY_EXPENSES: (params: string) => `${API_BASE_URL}/api/v1/reports/property-expenses${params}`,
    PROPERTY_STATEMENT: (params: string) => `${API_BASE_URL}/api/v1/reports/property-statement${params}`,
    TENANT_STATEMENT: (params: string) => `${API_BASE_URL}/api/v1/reports/tenant-statement${params}`,
    VACANT_RENTALS: `${API_BASE_URL}/api/v1/reports/vacant-rentals`,
    RENTERS_INSURANCE: `${API_BASE_URL}/api/v1/reports/renters-insurance`,
    MAINTENANCE_REQUESTS: (params: string) => `${API_BASE_URL}/api/v1/reports/maintenance-requests${params}`,
    CONTACTS: `${API_BASE_URL}/api/v1/reports/contacts`,
    RENTABILITY: (params: string) => `${API_BASE_URL}/api/v1/reports/rentability${params}`,
  },
};
